# Generated by Django 3.0.2 on 2020-01-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_auto_20200122_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agez',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthdayz',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_namez',
            new_name='first_name',
        ),
    ]
