# Generated by Django 3.0.2 on 2020-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_auto_20200122_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
